package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/spf13/cobra"
)

func newInitCmd() *cobra.Command {
	var (
		out     string
		k8s     string
		gitPath string
		force   bool
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Write .opsgraph.yaml for this repo (no service catalog required)",
		Long: "init writes a starter .opsgraph.yaml so `opsgraph ask` works without a hand-maintained\n" +
			"service map. Point --k8s at a kubectl YAML dump (directory or file):\n\n" +
			"  kubectl get deploy,event -o yaml > k8s-snapshot.yaml\n" +
			"  opsgraph init --k8s k8s-snapshot.yaml\n" +
			"  opsgraph ask",
		Example: `  opsgraph init
  opsgraph init --k8s k8s-snapshot.yaml
  opsgraph init --k8s ./k8s --git . --force`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if out == "" {
				out = ".opsgraph.yaml"
			}
			if gitPath == "" {
				gitPath = "."
			}
			if !force {
				if _, err := os.Stat(out); err == nil {
					return fail(1, "%s already exists (use --force to overwrite)", out)
				} else if err != nil && !os.IsNotExist(err) {
					return fail(2, "stat %s: %v", out, err)
				}
			}
			k8sPath := strings.TrimSpace(k8s)
			k8sEnabled := k8sPath != ""
			body := renderInitYAML(gitPath, k8sEnabled, k8sPath)
			if err := os.WriteFile(out, []byte(body), 0o644); err != nil {
				return fail(2, "write %s: %v", out, err)
			}
			abs, err := filepath.Abs(out)
			if err != nil {
				abs = out
			}
			cmd.Printf("wrote %s\n", abs)
			if k8sEnabled {
				cmd.Printf("next: opsgraph ask\n")
				cmd.Printf("      opsgraph pack --out ./incident   # shareable, bit-identical replay\n")
			} else {
				cmd.Printf("next: kubectl get deploy,event -o yaml > k8s-snapshot.yaml\n")
				cmd.Printf("      opsgraph init --k8s k8s-snapshot.yaml --force\n")
				cmd.Printf("      opsgraph ask\n")
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&out, "out", ".opsgraph.yaml", "config path to write")
	cmd.Flags().StringVar(&k8s, "k8s", "", "kubernetes snapshot directory or YAML file (enables the connector)")
	cmd.Flags().StringVar(&gitPath, "git", ".", "git repository path")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing config file")
	return cmd
}

func renderInitYAML(gitPath string, k8sEnabled bool, k8sPath string) string {
	var b strings.Builder
	b.WriteString("# Generated by opsgraph init. No service catalog required.\n")
	b.WriteString("# Native kubectl YAML is accepted (kind: List / Deployment / Event).\n")
	b.WriteString("#   kubectl get deploy,event -o yaml > k8s-snapshot.yaml\n")
	b.WriteString("#   opsgraph ask\n")
	b.WriteString("version: 1\n")
	b.WriteString("data_dir: .opsgraph/data\n")
	b.WriteString("default_since: 60m\n")
	b.WriteString("\n")
	b.WriteString("connectors:\n")
	b.WriteString("  git:\n")
	b.WriteString("    enabled: true\n")
	b.WriteString("    repo_path: " + strconv.Quote(gitPath) + "\n")
	b.WriteString("  kubernetes:\n")
	fmt.Fprintf(&b, "    enabled: %s\n", strconv.FormatBool(k8sEnabled))
	if k8sEnabled {
		b.WriteString("    snapshot: " + strconv.Quote(k8sPath) + "\n")
	} else {
		b.WriteString("    snapshot: \"\"\n")
	}
	return b.String()
}
